[package]
name = "rugraph"
version = "0.2.0"
edition = "2021"
authors = ["yangosoft"]
description = "Simple directed and multidirected graph library."



[[example]]
name = "example1"
crate-type = ["bin"]

[[example]]
name = "example2"
crate-type = ["bin"]

[dependencies]
