[package]
name = "rugraph"
version = "0.1.0"
edition = "2021"
authors = ["yangosoft"]
description = "Simple directed graph library."



[[example]]
name = "example1"
crate-type = ["bin"]

[dependencies]
